name-template: '$NEXT_MINOR_VERSION'
tag-template: '$NEXT_MINOR_VERSION'
categories:
  - title: '🚀 New Features'
    label: 'enhancement'
  - title: '🐞 Bug Fixes'
    label: 'bug'

change-template: '* $TITLE (via #$NUMBER) - @$AUTHOR'
template: |
  $CHANGES

  ## 👀 Links

  [Commits since $PREVIOUS_TAG](https://github.com/eroshenkoam/xcresults/compare/$PREVIOUS_TAG...master)
  
